-- MySQL Script generated by MySQL Workbench
-- Sat Jan  6 17:18:59 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sellerType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sellerType` (
  `idsellerType` INT NOT NULL,
  `typeName` VARCHAR(45) NULL,
  `whereEat` VARCHAR(45) NULL,
  PRIMARY KEY (`idsellerType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shopStyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shopStyle` (
  `idshopStyle` INT NOT NULL,
  `styleName` VARCHAR(45) NULL,
  PRIMARY KEY (`idshopStyle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`market`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`market` (
  `idmarket` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `supported` INT NULL,
  PRIMARY KEY (`idmarket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `market_idmarket` INT NOT NULL,
  PRIMARY KEY (`market_idmarket`),
  CONSTRAINT `fk_location_market1`
    FOREIGN KEY (`market_idmarket`)
    REFERENCES `mydb`.`market` (`idmarket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop` (
  `idshop` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `shopStyle_idshopStyle` INT NOT NULL,
  `location_market_idmarket` INT NOT NULL,
  PRIMARY KEY (`idshop`, `shopStyle_idshopStyle`),
  INDEX `fk_shop_shopStyle1_idx` (`shopStyle_idshopStyle` ASC),
  INDEX `fk_shop_location1_idx` (`location_market_idmarket` ASC),
  CONSTRAINT `fk_shop_shopStyle1`
    FOREIGN KEY (`shopStyle_idshopStyle`)
    REFERENCES `mydb`.`shopStyle` (`idshopStyle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shop_location1`
    FOREIGN KEY (`location_market_idmarket`)
    REFERENCES `mydb`.`location` (`market_idmarket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seller` (
  `idseller` INT NOT NULL,
  `type` INT NULL,
  `bandOnwer` VARCHAR(45) NULL,
  `sellerType_idsellerType` INT NOT NULL,
  `shop_idshop` INT NOT NULL,
  PRIMARY KEY (`idseller`, `sellerType_idsellerType`),
  INDEX `fk_seller_sellerType1_idx` (`sellerType_idsellerType` ASC),
  INDEX `fk_seller_shop1_idx` (`shop_idshop` ASC),
  CONSTRAINT `fk_seller_sellerType1`
    FOREIGN KEY (`sellerType_idsellerType`)
    REFERENCES `mydb`.`sellerType` (`idsellerType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seller_shop1`
    FOREIGN KEY (`shop_idshop`)
    REFERENCES `mydb`.`shop` (`idshop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`owner` (
  `idowner` INT NOT NULL,
  `market_idmarket` INT NOT NULL,
  PRIMARY KEY (`idowner`, `market_idmarket`),
  INDEX `fk_owner_market1_idx` (`market_idmarket` ASC),
  CONSTRAINT `fk_owner_market1`
    FOREIGN KEY (`market_idmarket`)
    REFERENCES `mydb`.`market` (`idmarket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`account` (
  `idaccount` INT NOT NULL,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phoneNumber` VARCHAR(45) NULL,
  `seller_idseller` INT NULL,
  `owner_idowner` INT NULL,
  INDEX `fk_account_owner1_idx` (`owner_idowner` ASC),
  PRIMARY KEY (`idaccount`),
  CONSTRAINT `fk_account_seller`
    FOREIGN KEY (`seller_idseller`)
    REFERENCES `mydb`.`seller` (`idseller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_owner1`
    FOREIGN KEY (`owner_idowner`)
    REFERENCES `mydb`.`owner` (`idowner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marketStyle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marketStyle` (
  `idmarketStyle` INT NOT NULL,
  `styleName` VARCHAR(45) NULL,
  PRIMARY KEY (`idmarketStyle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marketStyle_has_market`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marketStyle_has_market` (
  `marketStyle_idmarketStyle` INT NOT NULL,
  `market_idmarket` INT NOT NULL,
  PRIMARY KEY (`marketStyle_idmarketStyle`, `market_idmarket`),
  INDEX `fk_marketStyle_has_market_market1_idx` (`market_idmarket` ASC),
  INDEX `fk_marketStyle_has_market_marketStyle1_idx` (`marketStyle_idmarketStyle` ASC),
  CONSTRAINT `fk_marketStyle_has_market_marketStyle1`
    FOREIGN KEY (`marketStyle_idmarketStyle`)
    REFERENCES `mydb`.`marketStyle` (`idmarketStyle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marketStyle_has_market_market1`
    FOREIGN KEY (`market_idmarket`)
    REFERENCES `mydb`.`market` (`idmarket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
